export interface Database {
  public: {
    Tables: {
      cabinets: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          nom: string;
          adresse: string | null;
          ville: string | null;
          code_postal: string | null;
          telephone: string | null;
          email: string | null;
          siret: string | null;
          logo: string | null;
          couleur_primaire: string;
          couleur_secondaire: string;
          whapi_token: string | null;
          whapi_channel_id: string | null;
          actif: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          nom: string;
          adresse?: string | null;
          ville?: string | null;
          code_postal?: string | null;
          telephone?: string | null;
          email?: string | null;
          siret?: string | null;
          logo?: string | null;
          couleur_primaire?: string;
          couleur_secondaire?: string;
          whapi_token?: string | null;
          whapi_channel_id?: string | null;
          actif?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          nom?: string;
          adresse?: string | null;
          ville?: string | null;
          code_postal?: string | null;
          telephone?: string | null;
          email?: string | null;
          siret?: string | null;
          logo?: string | null;
          couleur_primaire?: string;
          couleur_secondaire?: string;
          whapi_token?: string | null;
          whapi_channel_id?: string | null;
          actif?: boolean;
        };
      };
      utilisateurs: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          cabinet_id: string;
          email: string;
          nom: string;
          prenom: string;
          role: string;
          telephone: string | null;
          actif: boolean;
          derniere_connexion: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          cabinet_id: string;
          email: string;
          nom: string;
          prenom: string;
          role?: string;
          telephone?: string | null;
          actif?: boolean;
          derniere_connexion?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          cabinet_id?: string;
          email?: string;
          nom?: string;
          prenom?: string;
          role?: string;
          telephone?: string | null;
          actif?: boolean;
          derniere_connexion?: string | null;
        };
      };
      projets: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          cabinet_id: string;
          created_by: string | null;
          titre: string;
          slug: string;
          description: string | null;
          adresse: string | null;
          ville: string | null;
          code_postal: string | null;
          type_bien: string | null;
          prix: number | null;
          surface: number | null;
          nb_pieces: number | null;
          nb_chambres: number | null;
          statut: string;
          date_ouverture: string | null;
          date_cloture: string | null;
          banner_image: string | null;
          images: string[] | null;
          contact_email: string | null;
          contact_phone: string | null;
          nombre_inscriptions: number;
          nombre_retenus: number;
          conditions_eligibilite: string[] | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          cabinet_id: string;
          created_by?: string | null;
          titre: string;
          slug: string;
          description?: string | null;
          adresse?: string | null;
          ville?: string | null;
          code_postal?: string | null;
          type_bien?: string | null;
          prix?: number | null;
          surface?: number | null;
          nb_pieces?: number | null;
          nb_chambres?: number | null;
          statut?: string;
          date_ouverture?: string | null;
          date_cloture?: string | null;
          banner_image?: string | null;
          images?: string[] | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          nombre_inscriptions?: number;
          nombre_retenus?: number;
          conditions_eligibilite?: string[] | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          cabinet_id?: string;
          created_by?: string | null;
          titre?: string;
          slug?: string;
          description?: string | null;
          adresse?: string | null;
          ville?: string | null;
          code_postal?: string | null;
          type_bien?: string | null;
          prix?: number | null;
          surface?: number | null;
          nb_pieces?: number | null;
          nb_chambres?: number | null;
          statut?: string;
          date_ouverture?: string | null;
          date_cloture?: string | null;
          banner_image?: string | null;
          images?: string[] | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          nombre_inscriptions?: number;
          nombre_retenus?: number;
          conditions_eligibilite?: string[] | null;
        };
      };
      documents_requis: {
        Row: {
          id: string;
          created_at: string;
          projet_id: string;
          nom: string;
          description: string | null;
          obligatoire: boolean;
          type_fichier: string[];
          taille_max: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          projet_id: string;
          nom: string;
          description?: string | null;
          obligatoire?: boolean;
          type_fichier?: string[];
          taille_max?: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          projet_id?: string;
          nom?: string;
          description?: string | null;
          obligatoire?: boolean;
          type_fichier?: string[];
          taille_max?: number;
        };
      };
      candidats: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          projet_id: string;
          statut: string;
          nom: string;
          prenom: string;
          email: string;
          telephone: string;
          date_naissance: string | null;
          lieu_naissance: string | null;
          nationalite: string | null;
          situation_familiale: string | null;
          adresse: string | null;
          ville: string | null;
          code_postal: string | null;
          profession: string | null;
          employeur: string | null;
          revenus_mensuels: number | null;
          type_contrat: string | null;
          anciennete_emploi: string | null;
          apport_personnel: number | null;
          montant_pret_sollicite: number | null;
          duree_pret: number | null;
          banque_actuelle: string | null;
          notes: string | null;
          score: number | null;
          documents: any[] | null;
          whatsapp_conversations: any[] | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          projet_id: string;
          statut?: string;
          nom: string;
          prenom: string;
          email: string;
          telephone: string;
          date_naissance?: string | null;
          lieu_naissance?: string | null;
          nationalite?: string | null;
          situation_familiale?: string | null;
          adresse?: string | null;
          ville?: string | null;
          code_postal?: string | null;
          profession?: string | null;
          employeur?: string | null;
          revenus_mensuels?: number | null;
          type_contrat?: string | null;
          anciennete_emploi?: string | null;
          apport_personnel?: number | null;
          montant_pret_sollicite?: number | null;
          duree_pret?: number | null;
          banque_actuelle?: string | null;
          notes?: string | null;
          score?: number | null;
          documents?: any[] | null;
          whatsapp_conversations?: any[] | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          projet_id?: string;
          statut?: string;
          nom?: string;
          prenom?: string;
          email?: string;
          telephone?: string;
          date_naissance?: string | null;
          lieu_naissance?: string | null;
          nationalite?: string | null;
          situation_familiale?: string | null;
          adresse?: string | null;
          ville?: string | null;
          code_postal?: string | null;
          profession?: string | null;
          employeur?: string | null;
          revenus_mensuels?: number | null;
          type_contrat?: string | null;
          anciennete_emploi?: string | null;
          apport_personnel?: number | null;
          montant_pret_sollicite?: number | null;
          duree_pret?: number | null;
          banque_actuelle?: string | null;
          notes?: string | null;
          score?: number | null;
          documents?: any[] | null;
          whatsapp_conversations?: any[] | null;
        };
      };
      chatbot_configs: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          projet_id: string;
          enabled: boolean;
          welcome_message: string;
          faq: any[] | null;
          suggestions: string[] | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          projet_id: string;
          enabled?: boolean;
          welcome_message?: string;
          faq?: any[] | null;
          suggestions?: string[] | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          projet_id?: string;
          enabled?: boolean;
          welcome_message?: string;
          faq?: any[] | null;
          suggestions?: string[] | null;
        };
      };
      chatbot_messages: {
        Row: {
          id: string;
          created_at: string;
          projet_id: string;
          candidat_id: string | null;
          session_id: string;
          role: string;
          message: string;
          ip_address: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          projet_id: string;
          candidat_id?: string | null;
          session_id: string;
          role: string;
          message: string;
          ip_address?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          projet_id?: string;
          candidat_id?: string | null;
          session_id?: string;
          role?: string;
          message?: string;
          ip_address?: string | null;
        };
      };
      activity_logs: {
        Row: {
          id: string;
          created_at: string;
          type: string;
          description: string;
          projet_id: string | null;
          candidat_id: string | null;
          utilisateur_id: string | null;
          metadata: any | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          type: string;
          description: string;
          projet_id?: string | null;
          candidat_id?: string | null;
          utilisateur_id?: string | null;
          metadata?: any | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          type?: string;
          description?: string;
          projet_id?: string | null;
          candidat_id?: string | null;
          utilisateur_id?: string | null;
          metadata?: any | null;
        };
      };
      app_settings: {
        Row: {
          id: string;
          key: string;
          value: string | null;
          description: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value?: string | null;
          description?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: string | null;
          description?: string | null;
          updated_at?: string;
        };
      };
    };
  };
}
